### ISSUE TITLE
Undeclared dependency on Moo

### ISSUE THREAD

**Issue by andk** [cafe01/Net-Moip-V2#1]
As per subject. Grep:

http://search.cpan.org/grep?release=Net-Moip-V2-0.05;string=Moo;n=1;C=0

Sample fail report:

http://www.cpantesters.org/cpan/report/79971505

HTH&&Thanks,

**Comment by cafe01** [comment]
Thank you! Fixed at 96201a2401e34e1b05f3954ea48e3f779d9cd98b
